### ISSUE TITLE
ERROR: function nvl(integer, integer) is not unique

### ISSUE THREAD

**Issue by legrandlegrand** [orafce/orafce#82] opened 2019-02-10 21:32 UTC
Hello,
using orafce 3.7 
here is what I get

> set search_path=oracle,public,pg_catalog; 
select nvl(1,1);
org.postgresql.util.PSQLException: ERROR: function nvl(integer, integer) is not unique
  Indice : Could not choose a best candidate function. You might need to add explicit type casts.
  Position : 8

I don't understand why there are 3 nvl definitions (one under puplic, 2 under oracle schema) ?
Thanks in advance for your help

Regards
PAscal

**Comment by okbob** [comment] 2019-02-11 09:31
Unfortunately, this is not a bug, but it is feature. I cannot to fix with current PostgreSQL functionality

a) Originally orafce used public schema - so the function from public schema is most old. This function uses polymorphic parameters and is very strict - first parameter should to use same type like second type. 

b) the functions from oracle schema allows two different types without necessity to explicitly cast - that I found be often used NVL(bigintcol, 0), NVL(numericcol, 0). Unfortunately, it in this moment the combination of int, int can be passed to two functions - and result is this bug.

It is paradox, it can be fixed by fourth function
<pre>
CREATE OR REPLACE FUNCTION oracle.nvl(int, integer)
 RETURNS int
 LANGUAGE sql
 IMMUTABLE
AS $function$
SELECT coalesce($1, $2)
$function$
</pre>

**Comment by okbob** [comment] 2019-02-11 09:38
please, check 3.8

**Comment by legrandlegrand** [comment] 2019-02-11 20:24
Thanks for your quick answer.

Now I understand it better, the correct version for our use case is the one found under public schema (with its polymorphic parameters). As our project is only using a very small subset of orafce functions, I'll try to write a custom orafce--xx.sql file restricted to a few functions all installed under oracle schema.

Regards
PAscal

**Comment by okbob** [comment] 2019-02-12 05:46
Sure, write own subset of orafce function can be (original) good enough solution.  Unfortunately, there is strong limit what is possible to implement in extensions and I cannot to across it. I wrote a patch, that can be a fix for Postgres  https://commitfest.postgresql.org/22/1911/, but it is long run

**Comment by legrandlegrand** [comment] 2019-02-12 19:40
Good idea!
but so long long way to go before getting it committed ;o(

**Closed** 2019-02-13 05:43 UTC
